addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( '596.txd' ) 
engineImportTXD( txd, 596 ) 
dff = engineLoadDFF('596.dff', 596) 
engineReplaceModel( dff, 596 )
end)